### ISSUE TITLE
it is not possible to install tpot without xgboost?

### ISSUE THREAD

**Issue by lizsz** [rhiever/tpot#109]
I have some issues installing xgboost. In the mean time I wanted to give a tpot a try, it seemed a very interesting concept. However, the installation of tpot failed while installing xgboost. I think it should be possible to run the tpot without some of the algorithms.

**Comment by rhiever** [comment]
What is the error that you're having with xgboost? What OS are you running?

If you're familiar with Python, you can remove xgboost by:

* Removing it from [this list](https://github.com/rhiever/tpot/blob/master/setup.py#L36)

* Removing it from the following lines/functions:
    * https://github.com/rhiever/tpot/blob/master/tpot/tpot.py#L41
    * https://github.com/rhiever/tpot/blob/master/tpot/tpot.py#L129
    * https://github.com/rhiever/tpot/blob/master/tpot/tpot.py#L545

then running `python setup.py install` in the base of the tpot directory.

I'm very curious to learn what issues you're having with xgboost, though. I only added it to TPOT because I was assured that it would be easy for everyone to install.

**Comment by lizsz** [comment]
Windows 7, LoadLibrary call fails due to some unknown (to me) dependency. 
here is [issue](https://github.com/dmlc/xgboost/issues/933) I submitted. Frankly, it is a weird issue and I believe it may be something wrong with my specific setup, although I can not quite figure out what exactly :(

**Comment by rhiever** [comment]
I'm going to close this issue and move the convo to the xgboost issue. Hopefully this can be addressed, else we may have to consider rolling back to using the sklearn GradientBoostingClassifier.

**Comment by rhiever** [comment]
Also: From reading your xgboost issue, it sounds like you could actually just disable xgboost by removing only these two lines in your TPOT install:

* https://github.com/rhiever/tpot/blob/master/tpot/tpot.py#L41

* https://github.com/rhiever/tpot/blob/master/tpot/tpot.py#L129
