### ISSUE TITLE
Add option to limit the Classifiers/Regressors that TPOT uses

### ISSUE THREAD

**Issue by orefeng** [rhiever/tpot#146]
TPOT is amazing! It is very powerful to provide a pipeline. But i wonder if i could limit tpot to one classifier, and only search for the best features and parameters? Because it is very time-consuming to traverse all the classifiers available.

**Comment by rhiever** [comment]
I like this idea. It should be possible to limit what kind of classifiers TPOT uses.

The main question is how we can implement this into the current TPOT interface. My first thought is to add a new boolean parameter to `__init__()` for each classifier -- each `True` by default -- that will allow the user to toggle the various classifiers on or off. This setup will work well with the command-line TPOT interface as well, as each classifier can be toggled off with a `--no-x-classifier` command.

However, that method seems to bloat the interface quite a bit, especially if we end up with 10+ classifiers implemented in TPOT. Any ideas on a better interface?

**Comment by orefeng** [comment]
I think maybe we can just add one parameter to __init__(). This parameter takes "None" as default value, and in this case various classifiers will be used. But when users want to limit what kind of classifiers TPOT uses, they should specify a classifier and assign the name or object of the classifier to the parameter.

**Comment by rhiever** [comment]
This was the other option I've been considering, but that seems hard to use, right? The user will have to specify certain values in the list (or dict), look up what those values should be, etc.

**Comment by KhaoticMind** [comment]
I like the one parameter idea. On the Python interface the parameter could be a list of classifiers instances (or classes). So you/we could just iterate over the list and call each classifier in order. If None, create a list with all classifiers on it.

**Comment by orefeng** [comment]
It is really a dilemma between ease of use and extendibility.

**Comment by kevinbsc** [comment]
An option to limit TPOT to one classifier (e.g., Random Forest) would be very helfpul.

**Comment by rhiever** [comment]
I've been thinking about this issue a little more and I wonder if we could take it a step further. Instead of allowing the user to specify what classifiers and operators within our existing set to use or not use, what if we provide an interface for the user to specify all the operators (and params that can evolve) during init?

The user essentially passes a list of sklearn-compatible objects and some metadata for each (e.g., what params to evolve in what ranges, whether it's a classifier or feature preprocessor, etc.), and we can parse them into the evolvable TPOT pipeline structure.

We would even specify our default TPOT operator set the same way, and allow it to be overriden by the user. I think such a setup would make TPOT much more flexible for us (no more need to write a separate file for every operator) and for the user (they can restrict or expand the operator and parameter space as they like).

cc @teaearlgraycold

**Comment by weixuanfu2016** [comment]
I agree with the one parameter idea. For the ease of use, if the parameter is set to specify classifiers/regressors, it can trigger a interface with a list of all the classifiers/regressors' names as well as their indexes and then let user to choose operators through their indexes . But I think it will be still not easy to use if the operators is more than 20+ in the future. Instead of interface, do you think a config file containing all these parameters (including ranges of params of operators if users want to specify them ) in _init_ is better? @rhiever
