### ISSUE TITLE
Warning: "n_components is too large"

### ISSUE THREAD

**Issue by rhiever** [rhiever/tpot#153]
I was running TPOT earlier and kept getting the following warning:

```
GP Progress:   0%|                                                                                | 0/10100 [00:00<?, ?pipeline/s]
n_components is too large: it will be set to 681
GP Progress:   1%|▍                                                                      | 63/10100 [00:14<42:15,  3.96pipeline/s]
n_components is too large: it will be set to 681
GP Progress:   1%|▋                                                                    | 97/10100 [00:37<1:46:22,  1.57pipeline/s]
```

@teaearlgraycold, can you please dig into the preprocessors to see which one is throwing this warning? We may need to put a cap on `n_components`.

**Comment by teaearlgraycold** [comment]
That error seems to be coming from FastICA.

Here's the sklearn code:

https://github.com/scikit-learn/scikit-learn/blob/06bf797c0deabe2a2f166d19abbd0c305da4d123/sklearn/decomposition/fastica_.py#L296

As it is right now that error will probably only show up if you have a ton of features and not very many actual data rows. I can just duplicate the following code from sklearn to avoid that print statement:

```Python
n, p = X.shape

if (n_components > min(n, p)):
        n_components = min(n, p)
```

Instead of what we're currently using:

```Python
n_components = min(n_components, len(training_features.columns.values))
```

**Comment by teaearlgraycold** [comment]
Actually I'm pretty sure that print statement should be a `UserWarning`, which we should be ignoring for FastICA.

Looking through the sklearn code for FastICA, I'm convinced this print statement is debug code mistakenly left in the module. The biggest hint is that `from __future__ import print_function` is no where in fastica_.py.

https://github.com/scikit-learn/scikit-learn/pull/6807
