### ISSUE TITLE
Parallelize cross validation as a provisional optimization

### ISSUE THREAD

**Issue by ghgr** [rhiever/tpot#302]
I propose setting the parameter _n_jobs_ to _num_cv_folds_ to get a sort of quick parallelism. When better solutions with dask are implemented we could set it again to 1

On _base.py_, __evaluate_individual_ method (line 575)
`cv_scores = cross_val_score(self, sklearn_pipeline, features, classes, cv=self.num_cv_folds, scoring=self.scoring_function)`

to 

`cv_scores = cross_val_score(self, sklearn_pipeline, features, classes, cv=self.num_cv_folds, scoring=self.scoring_function, n_jobs=self.num_cv_folds)`

**Comment by weixuanfu2016** [comment]
Thank you for sharing this nice tips. Based on the [User Guide](http://scikit-learn.org/0.17/modules/generated/sklearn.cross_validation.cross_val_score.html) of cross_val_score from  scikit-learn `njobs` parameter determines the CPU number to use in cross-validation while `cv` parameter determines the number of folds. Maybe adding `njobs` as another parameter in TPOT for paralleling the cross-validation with default of 1 since this way may use much more system resource. @rhiever

**Comment by ghgr** [comment]
Indeed that would be more precise. I proposed to make _njobs == num_cv_folds_ since the default number of cv folds in **tpot** is 3, and most machines (used for machine learning) have more than 3 cores. Just to make @minimumnz feel better not having idle cores [1] ;-)

[1] https://github.com/rhiever/tpot/issues/177

**Comment by rhiever** [comment]
We've been talking about adding a `n_jobs` parameter to TPOT for quite some time, which would basically do this. Perhaps we should just do that.

**Comment by Jonathan-Livingston-Seagull** [comment]
Would not be better to use the parallel processing capabilities of DEAP. i.e Each combination(preprocessor, algorithm, postprocessor, etc) is an individual in the population. Hence exploiting the DEAP features helps TPOT parallelizing through running an individual in seperate cores?

**Comment by rhiever** [comment]
We looked into using the multiprocessing capabilities of DEAP, but ran into issues with pickling lambda functions and a few other tricks we use in TPOT. Maybe @weixuanfu2016 can provide full details.

In the meantime, I've merged the PR into the `development` branch that exposes `n_jobs` for the cross-validation procedure.
