### ISSUE TITLE
Parallelize computation via DEAP?

### ISSUE THREAD

**Issue by fferroni** [rhiever/tpot#341]
Hello,

As I understand it, TPOT uses DEAP library in the backend. This library lists two options of parallelizing its toolbox computations, either using SCOOP or multiprocessing libraries.
https://github.com/DEAP/deap/blob/232ed17142da1c8bb6a39179018f8278b122aada/doc/tutorials/basic/part4.rst

I am wondering whether this has been considered as an avenue for parallelising TPOT, and if yes, if it's been successful?

Thanks!

**Comment by weixuanfu2016** [comment]
I tried to use both SCOOP and multiprocessing to parallelize TPOT but both did not work due to some functions (like lambda func) is not pickleable. So I used `pathos` to parallelize TPOT and it use `dill` instead of `pickle` for function serialization (check [this](http://matthewrocklin.com/blog/work/2013/12/05/Parallelism-and-Serialization) for more details) . Check this PR #338 for a demo for parallelizing TPOT.

**Comment by fferroni** [comment]
Hi,
Thanks! Looks good. The Travis build fails though?
Best,
Francesco

**Comment by weixuanfu2016** [comment]
I think it is because the Travis build does not have the pathos module.

**Comment by rhiever** [comment]
We're closing all questions that haven't been updated in a while. Please feel free to re-open this issue if your issue persists.
