### ISSUE TITLE
Remove the SelectKBest operator?

### ISSUE THREAD

**Issue by rhiever** [rhiever/tpot#424]
The `SelectKBest` operator uses a fixed `K` for the number of top features to keep. However, this causes an issue if `K` > the number of features in the dataset. Since `SelectPercentile` essentially does the same as `SelectKBest` but takes a percentile as the threshold, perhaps we should remove `SelectKBest` entirely.

cc @weixuanfu2016 @teaearlgraycold

**Comment by weixuanfu2016** [comment]
I think so. I checked source codes of both operators. As mentioned above, both operators do the same thing. Let's remove it.

**Comment by teaearlgraycold** [comment]
Since we no longer have code that can preprocess arguments, anything with a parameter that's randomly assigned and has some constraints based on the dataset should be removed/changed.

Maybe we could patch sklearn's `SelectKBest` to add support for floats in the range `[0.0, 1.0]`, where that range represents the proportion of features.

**Comment by rhiever** [comment]
@teaearlgraycold, that's essentially what `SelectPercentile` does.

**Comment by teaearlgraycold** [comment]
Are the selection criteria the same?
