### ISSUE TITLE
Pipeline pre-testing

### ISSUE THREAD

**Issue by unaigarciarena** [rhiever/tpot#528]
Hello everyone,

digging into the TPOT code, I have found the "_pre_test" function in the "decorators.py" script, which seems to be a decorator of other functions (i.e., mutation, crossover, and generation functions in "base.py"). This function appears to be run each time an unevaluated pipeline is generated, with a generic database generated from sklearn (pretest_X and pretest_Y). Am I right? 
If that is the case, isn't another way to test the syntactic and semantic correctness of the pipeline without requiring to actually apply it to an auxiliary database?

Thanks,

Unai.

**Comment by weixuanfu2016** [comment]
Yes, the `_pre_test` is to check correctness of the parameter combinations in the operators within pipeline since these parameter combinations are randomly generated in these three functions. For example, Dual formulation is only implemented for l2 penalty in `sklearn.linear_model.LogisticRegression`, but the unsupported combination (`dual=True, penalty='l1'` in this case) can be randomly generated and cause a invalid pipeline in optimization process. `_pre_test` was design to prevent it. 

But I hope there is a better way to check the correctness of parameter combinations without using `fit()`

**Comment by unaigarciarena** [comment]
Understood. Thank you very much.
