### ISSUE TITLE
Explain early stopping parameters in the documentation

### ISSUE THREAD

**Issue by MichaelMarkieta** [rhiever/tpot#75]
Is there use for an early stopping parameter? Where can it be best implemented? Should it be based on the previous n-rounds, or based on the internal validation evaluations? Something to think about...

**Comment by kadarakos** [comment]
TPOT could remember the top solution in after every generation and just roll back to the best one if it wasn't in the last generation. What do you think?

**Comment by rhiever** [comment]
@MichaelMarkieta, that's a tough question because we're never sure if TPOT has reached the global optimum or not. We could implement something to, say, stop TPOT if no better solution has been discovered in X generations or Y minutes, but it's difficult to gauge what X or Y should be because there's so many different problem domains that TPOT can be applied to. This is why I prefer the stop conditions to be controlled by the user: They decide how much time they want to commit to TPOT, and can stop execution at any point and see the best solution so far.

@kadarakos, that's what TPOT currently does. It maintains an archive of the best solutions discovered thus far and uses the best one at the end.

**Comment by MichaelMarkieta** [comment]
@rhiever I think this is a fair answer and you should close this issue/question. It would be good to add your comment to the introduction/readme/notes of the repository.

**Comment by rhiever** [comment]
I'll change this to an enhancement and modify the title correspondingly. Cheers!
